---

- name: define the full path to the kickstart file
  set_fact:
    virt_dom_os_ks_path: "{{ libvirt_temp_dir }}/{{ virt_dom_name }}/{{ virt_dom_os_kickstart | basename }}"

- name: create directory to kickstart file on the libvirt host
  file:
    state: directory
    dest: "{{ virt_dom_os_ks_path | dirname }}"
  delegate_to: "{{ libvirt_host }}"

- name: TODO do something nifty about the ISO to copy/pull it
  debug:
    msg: for now we assume it's already available at '{{ virt_dom_os_iso }}'

- name: create the kickstart file from the kickstart template
  template:
    src: "{{ virt_dom_os_kickstart }}.j2"
    dest: "{{ virt_dom_os_ks_path }}"
  delegate_to: "{{ libvirt_host }}"
