---
# Example of usage to create all the VMs in the inventory, without
# setting up again the libvirt host:
# ansible-playbook -i inventory libvirt_domain_create.yml --tags virtual_machines -K

- name: setup the libvirt hosts for libvirt automation
  hosts: libvirt_hosts
  gather_facts: false
  become: true
  tags: libvirt_hosts
  roles:
  - ericzolf.libvirt_automated.libvirt_setup

- name: create all necessary virtual machines
  hosts: virtual_machines
  gather_facts: false
  become: true
  tags: virtual_machines
  roles:
  - ericzolf.libvirt_automated.domain_create
  post_tasks:
  - name: refresh inventory after creation/start of VMs
    meta: refresh_inventory
  - name: output some variables to check proper inventory
    debug:
      var: "{{ item }}"
    loop:
    - ansible_host
    - libvirt_inv_name
    - libvirt_inv_title
    - libvirt_inv_description
